apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v9wvz76l5-dotnet-basic
  janus-idp.io/tekton: v9wvz76l5-dotnet-basic
  backstage.io/kubernetes-id: v9wvz76l5-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: v9wvz76l5-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
